# Generated by Django 4.2.5 on 2023-11-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_type",
            field=models.CharField(
                choices=[("income", "Income"), ("outcome", "Outcome")], max_length=250
            ),
        ),
    ]
